function labels_colors = defineLabelsColors_Nicola
%DEFINELABELSCOLORS_NICOLA   Labels and colors for plotting.
%   LABELS_COLORS = DEFINELABELSCOLORS_NICOLA returns preset labels and
%   colors for plotting. LABELS_COLORS is an N x 5 cell with tag, label,
%   color, second option for color, and line style in its columns. Use it
%   with MAKECOLORSLABELS.
%
%   See also MAKECOLORSLABELS and DEFINELABELSCOLORS_BALAZS.

%   Edit log: AK 7/01, BH 6/24/11

% Define colors and labels
%         TAG                               LabelName          Color              Color2    Line style 
labels_colors = { ...
        'All',                              'All',             [0   0   0],       [],       '-'; ...
        'Correct',                          'Correct',         [0.2 0.6 0],       [],       '-'; ...
        'Error',                            'Error',           [0.6 0.2 0],       [1 0 0],  '-'; ...
        'LeftChoice',                       'Left',            [0.2 0 0.9],       [],       '-'; ...
        'RightChoice',                      'Right',           [0.9 0 0.2],       [],       '-'; ...
        'Stimulus=[1 2 7 8]',               'Easy',            [0.3 0.9 0],       [],       '-'; ...
        'Stimulus=[3 4 5 6]',               'Diff',            [0.9 0.3 0],       [],       '-'; ...
        'Stimulus=[1 2 7 8]&Correct',     'Corr Easy',         [0.3 0.9 0],       [],       '-'; ...
        'Stimulus=[3 4 5 6]&Correct',     'Corr Diff',         [0.9 0.3 0],       [],       '-'; ...
        'Stimulus=[1 8]&Correct',         'Corr Easy',         [0.3 0.9 0.3],     [],       '-'; ...
        'Stimulus=[3 6]&Correct',         'Corr Med',          [0.3 0.6 0.9],     [],       '-'; ...
        'Stimulus=[4 5]&Correct',         'Corr Diff',         [0.9 0.3 0.3],     [],       '-'; ...
        'OdorRatio=[0100]&Correct',      'Corr Easy',          [0.3 0.9 0.3],     [],       '-'; ...
        'OdorRatio=[3268]&Correct',      'Corr Med',           [0.3 0.6 0.9],     [],       '-'; ...
        'OdorRatio=[32445668]&Correct',  'Corr Med',           [0.3 0.6 0.9],     [],       '-'; ...
        'OdorRatio=[4456]&Correct',      'Corr Diff',          [1 0.5 0.3],       [],       '-'; ...
        'OdorRatio=[0100]&Error',        'Err Easy',           [0.5 0.1 0.1],     [1 0 0],  '-'; ...
        'OdorRatio=[3268]&Error',        'Err Med',            [0.1 0.1 0.6],     [1 0 0],  '-'; ...
        'OdorRatio=[32445668]&Error',    'Err Med',            [0.8 0.2 0.2],     [1 0 0],  '-'; ...
        'OdorRatio=[4456]&Error',        'Err Diff',           [0.6 0.1 0.1],     [1 0 0],  '-'; ...
        'OdorRatio=[4456]',              '44/56',              [1 0.3 0.3],       [],       '-'; ...
        'OdorRatio=[3268]',              '32/68',              [0.3 0.3 0.9],     [],       '-'; ...
        'OdorRatio=[0100]',              '0/100',              [0.2 0.9 0.4],     [],       '-'; ...
        'OdorRatio=0',                    '0/100',             [0.15 0.9 0.1],    [],       '-'; ...
        'OdorRatio=32',                   '32/68',             [0.25 0.65 0.25],  [],       '-';   ...
        'OdorRatio=44',                   '44/56',             [0.25 0.55 0.45],  [],       '-';   ...
        'OdorRatio=50',                   '50/50',             [0.3 0.5 0.5],     [],       '-'; ...
        'OdorRatio=56',                   '56/44',             [0.25 0.45 0.55],  [],       '-';   ...
        'OdorRatio=68',                   '68/32',             [0.25 0.35 0.65],  [],       '-';   ...
        'OdorRatio=100',                  '100/0',             [0.15 0.1 0.9],    [],       '-'; ...
        'OdorRatio=0&Correct',            '0/100 corr',        [0.15 0.9 0.1],    [],       '-'; ...
        'OdorRatio=32&Correct',           '32/68 corr',        [0.25 0.65 0.25],  [],       '-';   ...
        'OdorRatio=44&Correct',           '44/56 corr',        [0.25 0.55 0.45],  [],       '-';   ...
        'OdorRatio=56&Correct',           '56/44 corr',        [0.25 0.45 0.55],  [],       '-';   ...
        'OdorRatio=68&Correct',           '68/32 corr',        [0.25 0.35 0.65],  [],       '-';   ...
        'OdorRatio=100&Correct',          '100/0 corr',        [0.15 0.1 0.9],    [],       '-';   ...
        'OdorRatio=0&Error',              '0/100 err',         [0.15 0.9 0.1],    [1 0 0],  '-';  ...
        'OdorRatio=32&Error',             '32/68 err',         [0.25 0.65 0.25],  [1 0 0],  '-';  ...
        'OdorRatio=44&Error',             '44/56 err',         [0.25 0.55 0.45],  [1 0 0],  '-';  ...
        'OdorRatio=56&Error',             '56/44 err',         [0.25 0.45 0.55],  [1 0 0],  '-';  ...
        'OdorRatio=68&Error',             '68/32 err',         [0.25 0.35 0.65],  [1 0 0],  '-';  ...
        'OdorRatio=100&Error',            '100/0 err',         [0.15 0.1 0.9],    [1 0 0],  '-'; ...
        'ResponseType=1',                 'Hit',               [0 0.75 0],        [],       '-';   ...
        'ResponseType=2',                 'False alarm',       [0.75 0 0],        [],       '-';   ...
        'ResponseType=3',                 'Correct reject',    [0 0 0.75],        [],       '-';   ...
        'ResponseType=4',                 'Miss',              [0 0 0],           [],       '-';   ...
        'Reward=1',                       'Likely reward',     [0 1 0],           [],       '-';   ...
        'Reward=2',                       'Unlikely reward',   [0 0.5 0],         [],       '-';   ...
        'Punishment=1',                   'Unlikely punishment',[0.5 0 0],        [],       '-';   ...
        'Punishment=2',                   'Likely punishment', [1 0 0],           [],       '-';   ...
        %         'TrialType=1',                    'Likely reward',     [0 0.8 0],         [],       '-';   ...
        %         'TrialType=2',                    'Likely punishment', [0.8 0 0],         [],       '-';   ...
        'TrialType=1',                    'Trial Type 1',     [0.9 0.4 0.2],         [],       '-';   ...
        'TrialType=2',                    'Trial Type 2',      [0 0 1],         [],       '-';   ...
        'TrialType=3',                    'Trial Type 3',      [0 0 0],         [],       '-';   ...
        'Outcome=1'                       'Reward',             [0 0.8 0],         [],       '-';   ...
        'Outcome=2'                       'Punishment',         [0.8 0 0],         [],       '-';   ...
        'FourKnights=1'                   'TT1 Rew',            [0 1 0],    [0.9 0.4 0.2], '-';  ...
        'FourKnights=2'                   'TT2 Rew',            [0 0.6 0],     [0 0 1],      '-'; ...
        'FourKnights=3'                   'TT1 Pun',            [1 0 0],    [0.9 0.4 0.2], '-'; ...
        'FourKnights=4'                   'TT2 Pun',            [0.6 0 0],      [0 0 1],     '-'; ...
        'EsaKnights=1'                   'TT1 Rew',            [0 1 0],    [0.9 0.4 0.2], '-';  ...
        'EsaKnights=2'                   'TT2 Rew',            [0 0.6 0],     [0 0 1],      '-'; ...
        'EsaKnights=3'                   'TT3 Rew',            [0 0.3 0],    [0 0 0], '-'; ...
        'EsaKnights=4'                   'TT1 Pun',            [1 0 0],      [0.9 0.4 0.2],     '-'; ...
        'EsaKnights=5'                   'TT2 Pun',            [0.6 0 0],    [0 0 1], '-'; ...
        'EsaKnights=6'                   'TT3 Pun',            [0.3 0 0],      [0 0 0],     '-'; ...
        'LvsR=1'                         'Go Left'             [0.7 0.2 0.0],         [],       '-';   ...
        'LvsR=2'                         'Go Right'            [0 0 0.8],         [],       '-';   ...
        'OvsN=1'                          'Old Sound'          [0.58 0.00 0.83],         [],       '-';   ...
        'OvsN=2'                          'New Sound'           [1 0 1],         [],       '-';   ...
        'RewLvsRewR=1'                    'Reward TT1'          [0 1 0],           [],      '-';   ...
        'RewLvsRewR=2'                    'Reward TT2'          [0 0.6 0],           [],      '-';   ...
        'PunLvsPunR=1'                    'Punishment TT1'      [1 0 0],           [],      '-';   ...
        'PunLvsPunR=2'                    'Punishment TT2'      [0.6 0 0],           [],      '-';   ...
        'RewLvsRvsN=1'                    'Reward TT1'          [0 1 0],           [],      '-';   ...
        'RewLvsRvsN=2'                    'Reward TT2'          [0 0.6 0],           [],      '-';   ...
        'RewLvsRvsN=3'                    'Reward TT3'          [0 0 0],           [],      '-';   ...
        'PunLvsPvsN=1'                    'Punishment TT1'      [1 0 0],           [],      '-';   ...
        'PunLvsPvsN=2'                    'Punishment TT2'      [0.6 0 0],           [],      '-';   ...
        'PunLvsPvsN=3'                    'Punishment TT3'      [0 0 0],           [],      '-';   ...  
};